"""drop file_report - reports feature removed

Revision ID: d41433f64433
Revises: dd572cf10a6f
Create Date: 2026-09-04 16:11:15.257099
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd41433f64433'
down_revision: str | None = 'dd572cf10a6f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_report_resolved'))

    op.drop_table('file_report')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_report',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('game_id', sa.VARCHAR(length=16), nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=16), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.Column('reporter', sa.VARCHAR(length=64), nullable=True),
    sa.Column('resolved', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_report_resolved'), ['resolved'], unique=False)

    # ### end Alembic commands ###
