"""initial schema

Revision ID: dd572cf10a6f
Revises: 
Create Date: 2026-09-04 13:55:50.389482
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'dd572cf10a6f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_release',
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    with op.batch_alter_table('app_release', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_release_channel'), ['channel'], unique=False)

    op.create_table('game',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('console', sa.String(length=3), nullable=False),
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('long_title', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_release',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('os', sa.String(length=16), nullable=False),
    sa.Column('arch', sa.String(length=16), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'os', 'arch', name='uq_tool_slot')
    )
    with op.batch_alter_table('tool_release', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_release_name'), ['name'], unique=False)

    op.create_table('artwork',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('variant', sa.Integer(), nullable=False),
    sa.Column('mime', sa.String(length=32), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('submitted_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'kind', 'variant', 'source', name='uq_artwork_slot')
    )
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artwork_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artwork_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_artwork_status'), ['status'], unique=False)

    op.create_table('cheat_file',
    sa.Column('game_id', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('submitted_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'source', name='uq_cheat_slot')
    )
    with op.batch_alter_table('cheat_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cheat_file_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cheat_file_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_cheat_file_status'), ['status'], unique=False)

    op.create_table('config_file',
    sa.Column('game_id', sa.String(length=16), nullable=False),
    sa.Column('cfg_version', sa.String(length=8), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('submitted_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'source', name='uq_config_slot')
    )
    with op.batch_alter_table('config_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_config_file_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_config_file_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_config_file_status'), ['status'], unique=False)

    op.create_table('file_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=16), nullable=True),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reporter', sa.String(length=64), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_report_resolved'), ['resolved'], unique=False)

    op.create_table('vmc_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('submitted_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'label', 'source', name='uq_vmc_slot')
    )
    with op.batch_alter_table('vmc_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vmc_file_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vmc_file_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_vmc_file_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vmc_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vmc_file_status'))
        batch_op.drop_index(batch_op.f('ix_vmc_file_sha256'))
        batch_op.drop_index(batch_op.f('ix_vmc_file_game_id'))

    op.drop_table('vmc_file')
    with op.batch_alter_table('file_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_report_resolved'))

    op.drop_table('file_report')
    with op.batch_alter_table('config_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_file_status'))
        batch_op.drop_index(batch_op.f('ix_config_file_sha256'))
        batch_op.drop_index(batch_op.f('ix_config_file_game_id'))

    op.drop_table('config_file')
    with op.batch_alter_table('cheat_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cheat_file_status'))
        batch_op.drop_index(batch_op.f('ix_cheat_file_sha256'))
        batch_op.drop_index(batch_op.f('ix_cheat_file_game_id'))

    op.drop_table('cheat_file')
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artwork_status'))
        batch_op.drop_index(batch_op.f('ix_artwork_sha256'))
        batch_op.drop_index(batch_op.f('ix_artwork_game_id'))

    op.drop_table('artwork')
    with op.batch_alter_table('tool_release', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_release_name'))

    op.drop_table('tool_release')
    op.drop_table('game')
    with op.batch_alter_table('app_release', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_release_channel'))

    op.drop_table('app_release')
    # ### end Alembic commands ###
