"""add game_list_entry table

Revision ID: f3c5712b2878
Revises: a27a211a27ad
Create Date: 2026-09-09 14:31:55.231481
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f3c5712b2878'
down_revision: str | None = 'a27a211a27ad'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_list_entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('console', sa.String(length=3), nullable=False),
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.Column('game_id', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('console', 'region', 'game_id', 'title', name='uq_gle_console_region_id_title')
    )
    with op.batch_alter_table('game_list_entry', schema=None) as batch_op:
        batch_op.create_index('ix_gle_console_title', ['console', 'title'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_list_entry', schema=None) as batch_op:
        batch_op.drop_index('ix_gle_console_title')

    op.drop_table('game_list_entry')
    # ### end Alembic commands ###
